eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled:  true
  instance:
    hostname: localhost

management:
  endpoint:
    health:
      enabled: true
      show-details: always
    env:
      enabled: false
    configprops:
      enabled: false

apo:
  client-id: Xchange_iPaaS_Stage
  service-token: eyJ4NXUiOiJpbXNfbmExLXN0ZzEta2V5LTEuY2VyIiwiYWxnIjoiUlMyNTYifQ.eyJpZCI6IlhjaGFuZ2VfaVBhYVNfU3RhZ2Vfc3RnIiwiY2xpZW50X2lkIjoiWGNoYW5nZV9pUGFhU19TdGFnZSIsInVzZXJfaWQiOiJYY2hhbmdlX2lQYWFTX1N0YWdlQEFkb2JlSUQiLCJ0eXBlIjoiYXV0aG9yaXphdGlvbl9jb2RlIiwiYXMiOiJpbXMtbmExLXN0ZzEiLCJvdG8iOiJmYWxzZSIsImV4cGlyZXNfaW4iOiIyNTkyMDAwMDAwMDAiLCJzY29wZSI6InN5c3RlbSxBUE8uKGFwcHJlZ2lzdHJ5Xy4rKSIsImNyZWF0ZWRfYXQiOiIxNTc0Njg3MDY5NzkyIn0.AAXx9JlqftHJUGu0FO95rfQGQtwbVA_IqeZ5FXmFqeHeseaicCxoSTL7U8yrt6QRw6JIhLxnQoec8vGrOtM8EW8EExYuuOIh-_Kfq5mgOwfP1IqezZ8Smj40niwTbbvKq5QuJwHt3JMFmRm5obJ5F3C6x5Ri1jYTj1CppviwIAuxMGGmK_SvR63shu2mq7M1J0RU4y6DuyrcfZXx5anru7O7XLngunxXH-Y02KWLdsT3g9rJplknoV1bgdDtCjtP8YXPtodIs_zvIvO2_a-aWd0eV6nGuRX9hRUQPZt9qTKjPLpVJJoGVBiIN_uJnEN4YM2cIIHqxEyxkd1n_2hSSw
  namespace: APO
  host: https://stage.postoffice.adobe.com/po-server/0.1/${apo.namespace}/${apo.client-id}/**/email
  client-secret: b90b92c0-8e7c-42de-b639-87fa54ad8dad

azure:
  endpoint-suffix: .blob.core.windows.net/
  perm-account-key: ${AZURE_PERMANENT_ACCOUNT_KEY}
  perm-account-name: ioexchangeappregistrydev
  temp-bucket-name: tmp
  temp-account-name: ioexchangenonprodtmp
  temp-account-key: m2CnclMXSLtfmUoa+iQ7GPjon8dyR1WhCAhmrKtPB9bqSuqWpdeDDmXsYqZaswIuObULo9n+T3+KsJrvjqYEeA==
  #temp-host: https://exchange-assets-stg.azureedge.net
  temp-host: https://ioexchangenonprodtmp.blob.core.windows.net
  host-url: https://ioexchange-cdn-dev.azureedge.net
  sign-expiry-sec: 7200
  #cdn-host-url: exchange-assets-stg.azureedge.net/
  cdn-host-url: ioexchange-cdn-dev.azureedge.net

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://ar-public-dev.mysql.database.azure.com:3306/vaccine-stage?useSSL=TRUE&requireSSL=FALSE&useUnicode=true&character_set_server=utf8mb4&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: arpublicdev@ar-public-dev
    password: vedcilbupRA321
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: Util-Service

ims:
  organizations-url: https://ims-na1-stg1.adobelogin.com/ims/organizations/v6
  profile-url: https://ims-na1-stg1.adobelogin.com/ims/profile/v1
  access-token-uri: https://ims-na1-stg1.adobelogin.com/ims/token/v1
  api-key: APP_AdobeExchange_STG_service
  ims-client-id: APP_AdobeExchange_STG_service
  ims-client-secret: ca909df6-e085-430b-8c70-9b43caa947f2
  ims-auth-code: eyJ4NXUiOiJpbXNfbmExLXN0ZzEta2V5LTEuY2VyIiwiYWxnIjoiUlMyNTYifQ.eyJpZCI6IkFQUF9BZG9iZUV4Y2hhbmdlX1NUR19zZXJ2aWNlX3N0ZzIiLCJjbGllbnRfaWQiOiJBUFBfQWRvYmVFeGNoYW5nZV9TVEdfc2VydmljZSIsInVzZXJfaWQiOiJBUFBfQWRvYmVFeGNoYW5nZV9TVEdfc2VydmljZUBBZG9iZUlEIiwidHlwZSI6ImF1dGhvcml6YXRpb25fY29kZSIsImFzIjoiaW1zLW5hMS1zdGcxIiwib3RvIjoiZmFsc2UiLCJleHBpcmVzX2luIjoiMjU5MjAwMDAwMDAwIiwiY3JlYXRlZF9hdCI6IjE1Nzg0MTA5MTIzMzQiLCJzY29wZSI6InN5c3RlbSJ9.Q5k5jpGNiqB8sZn8hJzCi-Cw5MuidwWbj14o6Rzn0uKADYFk2Fi3JECze98Uh1ut3FZlGuzDnBRFoHH6r3IDu2TXBIGD3Fworu2AfGY_JoiWC0ZNIuJ-KPKqOZqBbdQRLHcfWt6zdKpAOAooU9WvWhD1e9-h90ULXbOImM6aqxms1Bcomk8WcIIzNmKEOgmr9G8oWaEM8qEaI_D_wICbNIZVq1PX7Mza38xyTHlTbCYERthXH8oM2ZaKgCDn8OHCuBmksBHO-_d23ZeoWbWXyokHMbGJW6XPqSq7ST0cIOeoKE8Jc8PyaZ2N5poFsBLEt8R4KLseMqiM8F3f3KJJqQ

jilconfig:
  jil-api-host: https://bps-il-stage.adobe.io
  jil-base-path: /jil-api/v2/organizations/
  jil-api-key: APP_AdobeExchange_STG_service
  client-id: APP_AdobeExchange_STG_service
  service-token: eyJhbGciOiJSUzI1NiIsIng1dSI6Imltc19uYTEtc3RnMS1rZXktYXQtMS5jZXIiLCJraWQiOiJpbXNfbmExLXN0ZzEta2V5LWF0LTEiLCJpdHQiOiJhdCJ9.eyJpZCI6IjE2NTkzNDg0NDM2NDlfYWUyYTQ3Y2YtZWI5NS00MTE5LTgzMTEtNjEwMWRlNTBjNTQ2X2V3MSIsInR5cGUiOiJhY2Nlc3NfdG9rZW4iLCJjbGllbnRfaWQiOiJBUFBfQWRvYmVFeGNoYW5nZV9TVEdfc2VydmljZSIsInVzZXJfaWQiOiJBUFBfQWRvYmVFeGNoYW5nZV9TVEdfc2VydmljZUBBZG9iZUlEIiwiYXMiOiJpbXMtbmExLXN0ZzEiLCJhYV9pZCI6IkFQUF9BZG9iZUV4Y2hhbmdlX1NUR19zZXJ2aWNlQEFkb2JlSUQiLCJjdHAiOjAsInBhYyI6IkFQUF9BZG9iZUV4Y2hhbmdlX1NUR19zZXJ2aWNlX3N0ZzIiLCJydGlkIjoiMTY1OTM0ODQ0MzY1MF9mNGE5NTBmNS1lNDkwLTQ3MTYtYmU0YS04MmFhN2QwYWFiODJfZXcxIiwibW9pIjoiM2Q0N2I5OGUiLCJydGVhIjoiMTY2MDU1ODA0MzY1MCIsImV4cGlyZXNfaW4iOiI4NjQwMDAwMCIsImNyZWF0ZWRfYXQiOiIxNjU5MzQ4NDQzNjQ5Iiwic2NvcGUiOiJzeXN0ZW0sb3BlbmlkLGFkb2JlaW8uYXBwcmVnaXN0cnkud3JpdGUsYWRvYmVpby5hcHByZWdpc3RyeS5yZWFkLHJlYWRfb3JnYW5pemF0aW9ucyxhZGRpdGlvbmFsX2luZm8ucm9sZXMifQ.UB8cR0ZJLxKIs7A7V7vtlKdwVKwro5oaeSR8JmBJMPG0p_Q2ZtG6ieJsNsm7P3Ah4a9N-EwBBJXbKxk64qaGQhPGK4RDnYIGbxRGkuTFMC5MiUHElvlzOLZ-mhw3_14VhJk39TBzfaMB5FdMj7y2FIAJRvSOvRiJGXTi5dFmfrkCXUCLVLQX9SvVTviq0CyBkMYo2wzUsnOM4pSmw0lGvZBp2NCiUZVE6nVyeImCr75KEzuuiIh6LM6gxKhbfWpKsnw68kB1xOTSyFTHMfs0saDIS_0Lq57JVv3aIuFzApEd82s33JoEW8XTVG4pEpLP2DpqbSDG-VGXZS5gcLrVJw
  client-secret: ca909df6-e085-430b-8c70-9b43caa947f2
  token-buffer-minutes: 5

roles:
  admin:
    - org_admin
  developer:
    - LICENSE_DEV_ADMIN

scan:
  validate:
    filename: manifest.json
    maxSize: 314572800
    maxDepth: 11000
    readHiddenFile: true
    readHiddenDirectory: true
    hiddenFileList: .DS_STORE
    hiddenDirectoryList: __MACOSX
  clamd:
    host: 127.0.0.1
    port: 3310
    timeout: 2000
    isMock: true

management:
  endpoint:
    health:
      show-details: always

com:
  adobe:
    floodgate:
      env: STG
      callType: ASYNC
      retryInterval: 60
      retries: 25000
      imsClientId: APP_AdobeExchange_STG_service
      clients: IO_Global_Features
      apiKey: APP_AdobeExchange_STG_service
      imsClientSecret: ca909df6-e085-430b-8c70-9b43caa947f2
      imsClientCode: eyJ4NXUiOiJpbXNfbmExLXN0ZzEta2V5LTEuY2VyIiwiYWxnIjoiUlMyNTYifQ.eyJpZCI6IkFwcFJlZ2lzdHJ5LXNlcnZpY2Vfc3RnIiwiY2xpZW50X2lkIjoiQXBwUmVnaXN0cnktc2VydmljZSIsInVzZXJfaWQiOiJBcHBSZWdpc3RyeS1zZXJ2aWNlQEFkb2JlSUQiLCJ0eXBlIjoiYXV0aG9yaXphdGlvbl9jb2RlIiwiYXMiOiJpbXMtbmExLXN0ZzEiLCJvdG8iOiJmYWxzZSIsInNjb3BlIjoiYWNwLmNvcmUucGlwZWxpbmUsc3lzdGVtLEFQTy4oYXBwcmVnaXN0cnlfLispLGFkb2JlaW8uYXBwcmVnaXN0cnkud3JpdGUsYWRvYmVpby5hcHByZWdpc3RyeS5yZWFkLGFkZGl0aW9uYWxfaW5mby5yb2xlcyxyZWFkX29yZ2FuaXphdGlvbnMiLCJjcmVhdGVkX2F0IjoiMTU4OTAzMDk3ODI3MyJ9.NguG4oO3I07OA2AUdZkQPPFpb3lpQFL4WH5iGy3vAru3ah4Kve_6uyq9oFcTqMblKjBltBwpVAsrbM7H0DcNAWbtzwC6afB3sJnG4ohhHWsdZHmRbYYOFG6vvE1ji51IBhtcVSDQ04KIkqp1Xyb5sUWaz0myYXsZmaXBDDHa4VmHpaL4_Dh0U6ncwE9Zs-V-t-KklH9-xPCTUc7D_Yy4L9BQy5z4jWFKpJxT7227PaWui7s7cSVGUsDb9bgN5iNL5gCEmWTuxdhvgPGgGPMTzl_724nFScXGRZnNvIu-JKXgecFqQqAn2uTuMaIoiHW0F_7gRkSVMUmMnez6WcqauA
      serviceTokenCallback: fgCustomCallback
    asr:
      service-name: util-service
      service-client-id: util-serviceClientId
      logging:
        mask:
          headers: [x-gw-ims-email, x-gw-ims-display-name, x-gw-ims-first-name, x-gw-ims-last-name, x-gw-ims-user-id, Authorization, x-user-token]

genericapi:
  host: http://localhost:8080
  path: producer-api
  assetsUrl: ${genericapi.host}/${genericapi.path}/v2/assets
  assetsIdUrl: ${genericapi.assetsUrl}/%s
  xApiKey: APP_AdobeExchange_STG
  extensionsUrl: ${genericapi.host}/${genericapi.path}/v2/extensions
  extensionsIdUrl: ${genericapi.extensionsUrl}/%s
  assetsManifestUrl: ${genericapi.assetsUrl}/manifest

pipeline:
  ims-endpoint: https://ims-na1-stg1.adobelogin.com/ims/token/v1
  ims-client-id: AppRegistry-service
  ims-client-secret: ca909df6-e085-430b-8c70-9b43caa947f2
  ims-code: eyJ4NXUiOiJpbXNfbmExLXN0ZzEta2V5LTEuY2VyIiwiYWxnIjoiUlMyNTYifQ.eyJpZCI6IkFwcFJlZ2lzdHJ5LXNlcnZpY2Vfc3RnIiwiY2xpZW50X2lkIjoiQXBwUmVnaXN0cnktc2VydmljZSIsInVzZXJfaWQiOiJBcHBSZWdpc3RyeS1zZXJ2aWNlQEFkb2JlSUQiLCJ0eXBlIjoiYXV0aG9yaXphdGlvbl9jb2RlIiwiYXMiOiJpbXMtbmExLXN0ZzEiLCJvdG8iOiJmYWxzZSIsInNjb3BlIjoiYWNwLmNvcmUucGlwZWxpbmUsc3lzdGVtLEFQTy4oYXBwcmVnaXN0cnlfLispLGFkb2JlaW8uYXBwcmVnaXN0cnkud3JpdGUsYWRvYmVpby5hcHByZWdpc3RyeS5yZWFkLGFkZGl0aW9uYWxfaW5mby5yb2xlcyxyZWFkX29yZ2FuaXphdGlvbnMiLCJjcmVhdGVkX2F0IjoiMTU4OTAzMDk3ODI3MyJ9.NguG4oO3I07OA2AUdZkQPPFpb3lpQFL4WH5iGy3vAru3ah4Kve_6uyq9oFcTqMblKjBltBwpVAsrbM7H0DcNAWbtzwC6afB3sJnG4ohhHWsdZHmRbYYOFG6vvE1ji51IBhtcVSDQ04KIkqp1Xyb5sUWaz0myYXsZmaXBDDHa4VmHpaL4_Dh0U6ncwE9Zs-V-t-KklH9-xPCTUc7D_Yy4L9BQy5z4jWFKpJxT7227PaWui7s7cSVGUsDb9bgN5iNL5gCEmWTuxdhvgPGgGPMTzl_724nFScXGRZnNvIu-JKXgecFqQqAn2uTuMaIoiHW0F_7gRkSVMUmMnez6WcqauA
  endpoint: https://producer-pipeline-int-va7.adobe.net/
  producer-validation-topic: adobeio_exchange_appregistry_validation_events
  producer-publisher-profile-topic: adobeio_exchange_appregistry_producer_publisher_profile_dev
  producer-version-status-topic: adobeio_exchange_appregistry_producer_version_status_dev
  producer-status-change-topic: adobeio_exchange_appregistry_status_change_dev
  consumer-validation-topic: ccext_validation_events
  start-with-pipeline-consumer-enabled: false
  group: producergrouplocal
  connect-timeout: 5000
  read-timeout: 32000
  content-type: application/vnd.pipe.json.v2+json
  validation-key: do_validate
  profile-created-key: profile_created
  profile-updated-key: profile_updated
  version-published-key: version_published
  version-unpublished-key: version_unpublished
  app-status-change-key: app_status_change
  publisher-status-change-key: publisher_status_change
  source: AppRegistry
  locations:
    - VA6
    - VA7

sfdc:
  host: ipaasapi-dev.adobe-services.com
  path: sfdcCommonServices
  update-url: https://${sfdc.host}/${sfdc.path}/XChangeAddAppDetails?api_key=${sfdc.api-key}
  listing-url: https://${sfdc.host}/${sfdc.path}/XChangeSearchApps?api_key=${sfdc.api-key}
  api-key: l7xx806ee7f88ccb482a8d2959ecccc5df85
  private-key: ${IPAAS_PRIVATEKEY}
  authorization: eyJ4NXUiOiJpbXNfbmExLXN0ZzEta2V5LTEuY2VyIiwiYWxnIjoiUlMyNTYifQ.eyJpZCI6IkFQUF9BZG9iZUV4Y2hhbmdlX1NUR19zZXJ2aWNlX3N0ZzIiLCJjbGllbnRfaWQiOiJBUFBfQWRvYmVFeGNoYW5nZV9TVEdfc2VydmljZSIsInVzZXJfaWQiOiJBUFBfQWRvYmVFeGNoYW5nZV9TVEdfc2VydmljZUBBZG9iZUlEIiwidHlwZSI6ImF1dGhvcml6YXRpb25fY29kZSIsImFzIjoiaW1zLW5hMS1zdGcxIiwib3RvIjoiZmFsc2UiLCJleHBpcmVzX2luIjoiMjU5MjAwMDAwMDAwIiwiY3JlYXRlZF9hdCI6IjE1Nzg0MTA5MTIzMzQiLCJzY29wZSI6InN5c3RlbSJ9.Q5k5jpGNiqB8sZn8hJzCi-Cw5MuidwWbj14o6Rzn0uKADYFk2Fi3JECze98Uh1ut3FZlGuzDnBRFoHH6r3IDu2TXBIGD3Fworu2AfGY_JoiWC0ZNIuJ-KPKqOZqBbdQRLHcfWt6zdKpAOAooU9WvWhD1e9-h90ULXbOImM6aqxms1Bcomk8WcIIzNmKEOgmr9G8oWaEM8qEaI_D_wICbNIZVq1PX7Mza38xyTHlTbCYERthXH8oM2ZaKgCDn8OHCuBmksBHO-_d23ZeoWbWXyokHMbGJW6XPqSq7ST0cIOeoKE8Jc8PyaZ2N5poFsBLEt8R4KLseMqiM8F3f3KJJqQ
  client-id: APP_AdobeExchange_STG_service
  client-secret: ca909df6-e085-430b-8c70-9b43caa947f2
  token-buffer-minutes: 5
  grant_type: authorization_code
  ims-url: https://ims-na1-stg1.adobelogin.com/ims/token/v1

crypt:
  cryptoKey: ${CRYPTO_KEY}
  iv: ${IV}
